(function () {
  const session = JSON.parse(localStorage.getItem('demo_session') || 'null');
  if (!session) { alert('先にログインしてください'); return; }

  const now = new Date().toISOString();
  const existing = JSON.parse(localStorage.getItem('demo_stores') || '[]');

  const data = [
    { name: 'ギョウザ', location: '南行ってスグ右曲がる、橋と逆方向', note: '黄色の提灯（おでんの看板）中に入って商品入れる' },
    { name: 'アミックス', location: '南行ってすぐ右、右側、緑色が目印アサヒビールの看板のとこ階段上', note: '支払い最後にする' },
    { name: 'レモン', location: '南行ってすぐ右、白黒レモンの看板、左側', note: '空き瓶数える' },
    { name: 'エイジ', location: '光ビル3階', note: '' },
    { name: 'マーイッカ', location: '光ビル1階、奥', note: '' },
    { name: 'ブレーメン', location: '木屋町通のトリキの一個北、光ビル地下', note: '' },
    { name: 'タッタイス', location: '店の目の前の階段上がってすぐ右', note: '' },
    { name: 'ミック', location: '人妻レモンの近く', note: '' },
    { name: 'ラブジョイ', location: 'ロイヤルビル（観光ビルの手前）５階', note: '' },
    { name: 'サザン', location: '第一観光4階', note: '' },
    { name: 'シオン（紙音）', location: 'Zのビル8階', note: '' },
    { name: 'ゴールデン酒場', location: '木屋町通登ったとこ', note: '' },
    { name: 'シシクラ', location: 'たこ入道の通り', note: '' },
    { name: 'ジービー', location: '河原町通から入る。すしざんまいのビルの7階', note: '' },
    { name: 'オボス', location: '第一観光3階', note: '' },
    { name: 'アチャコチャ', location: 'たこ入道の通り', note: '' },
    { name: 'オトミ', location: '北に上がって突き当たり左のおでん屋', note: '' },
    { name: 'ラクユウ', location: 'たこ入道の通り', note: '' },
    { name: 'ロッジ', location: 'らくゆうの隣、青緑の外観', note: '' },
    { name: 'ニシウオ', location: 'たこ入道の通り、数えない', note: '' },
    { name: 'ルナ', location: 'ヌフの隣', note: '' },
    { name: 'ルイス', location: 'たこ入道の通り', note: '' },
    { name: 'スイッチ', location: 'たこ入道の通り、通り抜けて左', note: '' },
    { name: 'スカイ', location: 'XGの向かい側', note: '' },
    { name: 'ハロードリー', location: 'たこ入道の通り', note: '樽の依頼多い' },
    { name: 'ユキトモ', location: 'ミルクホールと同じビル', note: '' },
    { name: 'ツーエイト（two eight）', location: '立ち飲み屋のビル（オーシャンビル4階）', note: '' },
    { name: 'シマン', location: 'すぐ北の右側、中に入って冷たくない大瓶から渡す、瓶数えて引く', note: '' },
    { name: 'ミルクホール', location: 'オリオンの看板すぐ横、右手、店の北、階段上がって左', note: '' },
    { name: 'リット', location: 'アルファのビル3階', note: '' },
    { name: 'スターダスト', location: 'ままやの通り（しゅず通り）の奥', note: '南側から行く' },
    { name: 'プレシャーズ', location: '店の真南、赤色', note: '' },
    { name: 'ミツヤ', location: '大豊ラーメンの手前のビル2階', note: '' },
    { name: 'ミラグロス', location: 'タバコ屋のビル5階', note: '' },
    { name: 'ノック', location: 'タバコ屋のビル3階（看板無い）', note: '' },
    { name: 'メイテイ', location: 'ドンキ曲がってケバブ屋から寺町に出て左、すぐ曲がった路地のとこ', note: '' },
    { name: 'トモ（智）', location: 'マックの奥、ニュー木屋町ビル地下', note: '中にタル入れる' },
    { name: 'キセノン', location: '13番路地（駐車場の隣、ここのめの奥）', note: '' },
    { name: 'エハコ', location: '13番路地（駐車場の隣、ここのめの奥）', note: '下の勝手口からやりとりする' },
    { name: 'ジェリービーンズ', location: '店の東、粘土色ビル2階、オレンジ看板、北から行く', note: '北から行く' },
    { name: 'フィッシュ', location: 'イトウビルの南にある路地、右側にエレベーター、地下一階に降りて右', note: '' },
    { name: 'アジュール', location: 'イトウビル3階', note: '南側から行く' },
    { name: 'ベイル', location: 'ロイヤルビル4階', note: '' },
    { name: 'スペード', location: 'イトービル4階、DOLL嬢の隣', note: '' },
    { name: 'ドルジョー', location: 'アジュールビル4階', note: '' },
    { name: 'ガレージ19', location: 'ムーキーの右隣ビル、2階', note: '' },
    { name: 'マスノヤ（枡ノ矢）', location: 'きぬたビルの横を抜けて先斗町通りを左、公園より手前', note: '' },
    { name: 'ウエダウメ', location: 'ままやの道抜けたあたり、東側に白いランプ看板で上田梅、民家の見た目', note: '' },
    { name: 'ロイヤルシーン', location: 'ロイヤルビル10階', note: '' },
    { name: 'ビーピーエム', location: 'オーシャンビル（立ち飲み屋のビル）2階', note: '' },
    { name: 'チリエージョ', location: '御射山公園のちょい北', note: '' },
    { name: 'カメハメハ', location: 'メイテイの2つ隣、ファミマ横抜けて左曲がってすぐ右のお好み焼き屋', note: '' },
    { name: 'バックアレイ', location: '弘の近くのビル、牛角ビル', note: '' },
    { name: 'ハクビ', location: 'ままや抜けて左、ななめの階段2階', note: '南側から行く' },
    { name: 'ワッツニュー', location: 'ままやの通り抜けて左、小道入って英語の看板', note: '' },
    { name: 'ヒデタコ', location: '大豊ラーメンの横', note: '' },
    { name: 'ベラミ', location: 'たばこ屋の通り、真ん中ら辺の左手にある階段2階', note: '' },
    { name: 'ママトルティ', location: '15番路地、パイレーツの通り、右側階段上', note: '' },
    { name: 'アーリオ（aglio）', location: 'ここのめのビル5階', note: '' },
    { name: 'アルファ', location: '蛸薬師（ブラボーの横の通り）にある王将のビル2階', note: '' },
    { name: 'ネオ', location: 'ONEの真西', note: '南側から行く / ノセミネラルソーダ（太いやつ）' },
    { name: 'タートルサワー', location: '御射山公園の横、麺屋高倉のビル、一番遠い', note: '' },
    { name: 'バーコード', location: '自販機ある通路（少し北）を抜けたところ2階、裏側', note: '' },
    { name: 'ベル', location: '観光ビルの隣、ロイヤルビル4階', note: '' },
    { name: 'クラブシャルム', location: 'ヌフの向かいのビル、踊り場あるビル２階', note: '' },
    { name: 'ワットエバー', location: 'ポリーズラボの奥、右手側、引き戸', note: '' },
    { name: 'スプリング', location: '六角のリカマン超えた六角テラスビルの３階', note: '' },
    { name: 'サンサンゴ（335）', location: 'かぶれんまで行く途中にある右側のビル、青い看板、3階', note: '' },
    { name: 'ブラウンシュガー', location: 'たいらの上', note: '' },
    { name: 'タイラ', location: 'かぶれん下って左手、先斗町ビル２階', note: '' },
    { name: 'ラニカフェ', location: 'Z超えて立体駐車場を左に入る、ホテルの前あたりの右手', note: '' },
    { name: 'シークス', location: '橋渡って1つ目の左に曲がる道入って右手のカモガワビル8階', note: '' },
    { name: 'ブライビー', location: '長浜ラーメンの横の階段、レモンの看板、3階', note: '' },
    { name: 'フラット', location: '蛸薬師通り（ジョーカーを真西に入る）の王将の横の白いビル2階', note: '' },
    { name: 'ベル（ゲイバー）', location: 'タカセビルの地下、三条大橋の前', note: 'ゲイバー' },
    { name: 'ワン', location: '切り通しの右側にある白看板でONE、１階', note: '' },
    { name: 'ロジック', location: 'タバコ屋の一個手前のビル、階段で上がって3階', note: '' },
    { name: 'ジョーカー', location: '先斗町の駐輪場の手前、チャリ', note: '' },
    { name: 'セントジェームズクラブ', location: '智の裏手のビル、ドトールの細道と木屋町通の交わるとこ', note: '' },
    { name: 'サンカイ', location: 'ヒートのビル3階', note: '' },
    { name: 'ワダチ（轍）', location: '北の橋渡って正面のラーメン屋', note: '' },
    { name: 'にゃんだふる', location: 'スペードの横', note: '' },
    { name: 'カウンターバーGB', location: 'すしざんまいの通り（交番前の通り）の途中にあるビルの1番上の階', note: '' },
    { name: 'フクロウ（福ロウ）', location: 'ニューみまさと同じビル、奥に入っていって3階', note: '' },
    { name: 'アダチヤ', location: '松屋の交差点北上、右手側の綺麗なビル、青い看板、地下', note: '' },
    { name: 'ニューミマサ', location: '青いのれん、チャリ、春水堂の２個北の通り左', note: '樽が多い' },
    { name: 'セブンスポット（7spot）', location: '交番と北のビルにある先斗町に抜ける路地の真ん中', note: '' },
    { name: 'チキュウヤ', location: '河原町駅のちょい下', note: '' },
    { name: 'リレイズ', location: '河原町駅のちょい下', note: '' },
    { name: 'ムーキー', location: 'エディオンの南', note: '外で待って気づいてもらうまで待つ' },
    { name: 'エンジェル', location: 'タバコ屋のビル4階', note: '' },
    { name: 'クロベエ', location: 'たばこ屋の通り真ん中らへん、赤提灯、左側', note: '' },
    { name: 'ムギ', location: 'OPAの裏、赤い看板の居酒屋', note: '' },
    { name: 'センノカゼ', location: 'OPAの裏のラーメン屋', note: '瓶をカウンターに乗せる、タルは中' },
    { name: 'カフェコラボ（木屋町）', location: 'ロイヤルパーク左、ラーメン屋横のビル、右手の3階', note: '' },
    { name: 'ランド', location: '春水側から行ってファミマ右、すぐの通りを右、おでんの奥、赤色ビル2階', note: '' },
    { name: 'クラブZ', location: 'ZAZAPUBの右2階、チャリ、北', note: '' },
    { name: 'ハート', location: '第二観光5階', note: '' },
    { name: 'ワンディー', location: 'エディオンの横、２階', note: '' },
    { name: 'ダート', location: 'ここのめビルの手前、タバコ屋のビル、エレベーター3階', note: '' },
    { name: 'ブルックリン', location: 'エンパイアビル(宴会したとこ)の6階', note: '' },
    { name: 'アズ（A..z）', location: 'ヒートと同じビル四階', note: '' },
    { name: 'エックスジー', location: 'ラグナの手前、エントランス広いビルの4階、光ってる方', note: '' },
    { name: 'ヒート', location: '六角通、少し奥の鬼の看板、左手に見える', note: '' },
    { name: 'ポリーズラボ（木屋町）', location: 'ホルモン千葉まで行かない。橋超えて細い道まっすぐ', note: '空き瓶数えて、1.領収書に差し引き金額書く、2.2枚のレシートにも書く、3.空き瓶数とその値段をメモっておく' },
    { name: 'アレフ', location: 'クラブZの先、突き当たりのローマ字看板', note: '' },
    { name: 'パイレーツ', location: 'ここのめのビルの奥', note: '' },
    { name: 'ウミノナカ', location: '335の向かい側、角のビルの地下', note: '' },
    { name: 'アンバー（琥珀）', location: 'ここのめのビルの奥', note: '' },
    { name: 'グランドライン', location: '交番の北レンガ調のビル5階', note: '' },
    { name: 'ブラボー', location: '交番手前の橋（ジョーカーの前）曲がってすぐ、駐輪場の前のPLEXUSビルの6階', note: '' },
    { name: 'スミカ', location: '富小路の方は、蛸薬師抜けて錦通り三本跨いだ位で左', note: '' },
    { name: 'ヨアソビ', location: '第二観光七階', note: '' },
    { name: 'ラブ', location: '第一観光ビルと第二観光ビルの間', note: 'ガールズバー' },
    { name: 'ラブ&ジョイ', location: 'ロイヤルビル5階', note: '' },
    { name: 'ピース', location: '第二観光ビル2階', note: '' },
    { name: 'チックタック', location: '第一観光ビル５階', note: '' },
    { name: 'サルート', location: '木屋町通北上、でかいビル4階', note: '' },
    { name: 'コー（Co.）', location: 'ピンク看板、ホルモン肉料理屋の隣の小道、サルートビルの近く', note: 'ガルバ' },
    { name: 'コウラク', location: 'サルートビルの地下、チャリで行く', note: 'エレベーターで行けない' },
    { name: 'バモス', location: '六角通', note: '' },
    { name: 'ショッカー', location: '六角通りの業スー横のビル二階、右手', note: '' },
    { name: 'ファーム', location: 'ヒートのビル2階', note: '' },
    { name: 'エムアンドエム（M&M）', location: 'タナカコーヒーの向かいのビル、3階', note: '' },
    { name: 'ハイエスト', location: 'ヌフのビル5階', note: '' },
    { name: 'ドランク', location: '六角通、ショッカーと同じビル4階', note: '' },
    { name: 'モアナ', location: '六角通', note: '' },
    { name: 'フレアトール', location: '六角通', note: '' },
    { name: 'ラグナ', location: '六角通り、白いビル3階、青い階段', note: '' },
    { name: 'カフェコラボ（六角）', location: '六角通の一つ上、ラーメン屋の右の細い階段', note: '' },
    { name: 'ブー', location: 'ポリーズラボと同じビル、2階', note: '' },
    { name: 'ポリーズラボ（六角）', location: 'ムーキーの一つ北の通り、赤と緑の看板', note: '' },
    { name: 'ユーボックス', location: 'メイドカフェのビル4階', note: '先に空数言ってくれる、一応数えとく' },
    { name: 'ゼロワン', location: 'ユーボックスの隣のビル2階、ファンタジスタのビル', note: '' },
    { name: '三条クラブ', location: 'ユーボックスの次曲がってすぐ左（角）3階、入ったら厨房行く', note: '' },
    { name: 'ヌフ', location: '北車屋通り（タナカコーヒー通り）、ノアと同じ建物2階', note: '空瓶出たらその場で計算する商品渡す⇒お金だけ貰って外でお釣り計算⇒渡す' },
    { name: 'ブラウンシュガー（北）', location: '平の手前、右側のビル2階', note: '' },
    { name: 'クラブノア', location: 'タナカコーヒーの横、白いビル、階段少し降りたとこにある', note: '' },
    { name: 'キョウカ', location: '北車屋通り、ムラサキの左のビル、チャイナドレス', note: '' },
    { name: 'ムラサキ', location: '北車屋通りの右手側奥の方、緑の看板', note: '' },
    { name: 'アイズ', location: '北車屋、キョウカと同じビル、ムラサキの隣', note: '' },
    { name: 'バリィ', location: 'ヌフのビル4階', note: '' },
    { name: 'トリシゲ', location: 'タナカコーヒーの横', note: '' },
    { name: 'ビアバーミヤマ', location: 'スターダストの3階', note: '' },
    { name: 'ミヤマ', location: 'タナカコーヒーの前', note: '' },
    { name: 'トーストオブザ・タウン', location: '13番路地手前の白色ビル手前3階', note: '' },
    { name: 'アイドリーム', location: 'ソクハイ永末の前のビル4階', note: '場所知らん' },
    { name: 'クレドール', location: '花見小路通、ローソン2階', note: '' },
    { name: 'イブ', location: '花見小路、リカワンの通りまっすぐで、花見小路超えて左側リアライズ花見小路ビル', note: '' },
    { name: 'ルイス（デイトナ）', location: 'イブのビル1階', note: '' },
    { name: 'オレンチ', location: 'ソクハイ永末の横、エンゼルビル5F', note: '' },
    { name: 'バナナ', location: 'いっせん洋食（木のでかい看板）を曲がって二つ目の角右、井みねビル2階', note: '' },
    { name: 'ドラゴン', location: 'わたぢびる、いっせん洋食の角を右', note: '' },
    { name: 'ゲート', location: '花見小路を北に進んで、綺麗な建物を右、クライム祇園ビル２階', note: '' },
    { name: 'キス', location: '一銭洋食曲がってまっすぐ、橋越えて左側、白馬のビル、３階', note: '入って右のスタッフルームに商品入れる' },
    { name: 'オウカ', location: 'かおるの通りを北上してパーキングの二個横くらいにあるビル、左手', note: '' },
    { name: 'カオル', location: '花見小路の手前の筋（一銭洋食の一個奥）を曲がって北上、噴水のビル超えてすぐ左手、２階', note: '' },
    { name: 'ジラフ', location: 'うさぎの小部屋と同じビル、コンラッドビル二階', note: '' },
    { name: 'フルフッキング', location: 'マック超えた橋を左に行き、寺で曲がる', note: '' },
    { name: 'ウサギノコベヤ', location: '八坂神社の手前、調べたら出てくる', note: '' },
    { name: 'ディスコ', location: 'イブの道路挟んで南向かいのビル四階', note: '日曜しか来ない' },
    { name: 'カツヒコ', location: 'リカワン超えてすぐ左の突き当たり、見た目綺麗なマンション', note: '' },
    { name: 'ジユウヤバディ', location: '幸生ビル4階', note: '' },
    { name: 'ユー（yu）（⚠️）', location: '祇園の奥の方', note: '' },
    { name: 'アポル（APOL）', location: 'クライム祇園ビル5階', note: '' },
    { name: 'マザームーン', location: '花見小路入ってすぐ右、青色円柱のビル1階左側', note: '' },
    { name: 'バロン', location: 'マザームーンのちょい奥、左手、ユウキビル二階', note: '' },
    { name: 'ビーズビー', location: 'アサヒ6号館4階、川端通沿い、祇園四条9番出口正面', note: '' },
    { name: 'ラウンド', location: '一銭洋食曲がって右手の八百屋のビル3階', note: '' },
    { name: 'ルナ（祇園）', location: '一銭洋食の角を右に曲がって左手、自販機あるビル、金色の扉', note: '' },
    { name: 'ケー（K）', location: 'ローソンの近く、今井アートビル', note: '' },
    { name: 'ワン（祇園）', location: 'かおるのむかい側', note: '' },
    { name: 'シノブ', location: 'オウカの手前、レンガのビル（八坂ビル）3階', note: '' },
    { name: 'イチゴイチエ', location: 'みゆきビル3階、カツヒコを東に行くと左に見える', note: '' },
    { name: 'アマネ(弥)', location: 'ソクハイ中末の目の前にある駐車場の脇道入ってすぐ左、のれんに店名', note: '' },
    { name: 'リップ', location: 'マザームーンの向かいの横道入ってすぐ左、3階', note: '' },
    { name: 'カルシウムハウス', location: 'シークスのビル（祇園行く道の左手にあるたい焼き屋曲がって右手）', note: '' },
    { name: 'ナッツ', location: 'キスと同じビル2階', note: '' },
    { name: 'ユウコ', location: '花見奥まで行って綺麗なビルを右(新橋通り)、左手に螺旋の白いビル2階', note: '' },
    { name: 'ジャミン', location: 'キスと同じ階', note: '' },
    { name: 'スマイル', location: 'イブのビル2階', note: '' },
    { name: 'ルーキーズ', location: 'スリーエスビル3階', note: '' },
  ];

  const newStores = data.map(s => {
    let memo = '';
    if (s.location) memo += '【場所】' + s.location;
    if (s.note) memo += (memo ? '\n' : '') + '【備考】' + s.note;
    return {
      id: crypto.randomUUID(),
      user_id: session.id,
      name: s.name,
      address: '',
      latitude: 35.0053,
      longitude: 135.7731,
      memo: memo || undefined,
      created_at: now,
      updated_at: now,
    };
  });

  localStorage.setItem('demo_stores', JSON.stringify([...existing, ...newStores]));
  alert(newStores.length + '件の店舗を追加しました！ページをリロードしてください。');
})();

